[transform]

[model]
type = 'SimpleCNN'
num_classes = 100
#load = false
load = 'runs/vanilla_2025-03-08_18-19-34_/model.ckpt'
#load = 'runs/weight_decay_2025-03-08_22-34-45_/model.ckpt'

[model.optimizer]
lr = 0.002
weight_decay = 0.02

[train]
num_epoch = 100

[data_set]
data_set = 'CIFAR100'
root = "D:\\cifar100"
train = true

[data_set_test]
data_set = 'CIFAR100'
root = "D:\\cifar100"
train = false

[data_loader]
num_workers = 6
batch_size = 64
shuffle = true

[data_loader_test]
num_workers = 6
batch_size = 64
shuffle = false